/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as MenuRouteImport } from './routes/menu'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ReportsIndexRouteImport } from './routes/reports/index'
import { Route as QueueOrdersIndexRouteImport } from './routes/queue-orders/index'
import { Route as PosIndexRouteImport } from './routes/pos/index'
import { Route as OrdersIndexRouteImport } from './routes/orders/index'
import { Route as ExpensesIndexRouteImport } from './routes/expenses/index'
import { Route as ExpensesNewRouteImport } from './routes/expenses/new'
import { Route as ExpensesExpenseIdRouteImport } from './routes/expenses/$expenseId'
import { Route as DemoTanstackQueryRouteImport } from './routes/demo/tanstack-query'
import { Route as manageproductsProductsIndexRouteImport } from './routes/(manage products)/products/index'
import { Route as manageproductsCategoriesIndexRouteImport } from './routes/(manage products)/categories/index'

const MenuRoute = MenuRouteImport.update({
  id: '/menu',
  path: '/menu',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsIndexRoute = ReportsIndexRouteImport.update({
  id: '/reports/',
  path: '/reports/',
  getParentRoute: () => rootRouteImport,
} as any)
const QueueOrdersIndexRoute = QueueOrdersIndexRouteImport.update({
  id: '/queue-orders/',
  path: '/queue-orders/',
  getParentRoute: () => rootRouteImport,
} as any)
const PosIndexRoute = PosIndexRouteImport.update({
  id: '/pos/',
  path: '/pos/',
  getParentRoute: () => rootRouteImport,
} as any)
const OrdersIndexRoute = OrdersIndexRouteImport.update({
  id: '/orders/',
  path: '/orders/',
  getParentRoute: () => rootRouteImport,
} as any)
const ExpensesIndexRoute = ExpensesIndexRouteImport.update({
  id: '/expenses/',
  path: '/expenses/',
  getParentRoute: () => rootRouteImport,
} as any)
const ExpensesNewRoute = ExpensesNewRouteImport.update({
  id: '/expenses/new',
  path: '/expenses/new',
  getParentRoute: () => rootRouteImport,
} as any)
const ExpensesExpenseIdRoute = ExpensesExpenseIdRouteImport.update({
  id: '/expenses/$expenseId',
  path: '/expenses/$expenseId',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoTanstackQueryRoute = DemoTanstackQueryRouteImport.update({
  id: '/demo/tanstack-query',
  path: '/demo/tanstack-query',
  getParentRoute: () => rootRouteImport,
} as any)
const manageproductsProductsIndexRoute =
  manageproductsProductsIndexRouteImport.update({
    id: '/(manage products)/products/',
    path: '/products/',
    getParentRoute: () => rootRouteImport,
  } as any)
const manageproductsCategoriesIndexRoute =
  manageproductsCategoriesIndexRouteImport.update({
    id: '/(manage products)/categories/',
    path: '/categories/',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/menu': typeof MenuRoute
  '/demo/tanstack-query': typeof DemoTanstackQueryRoute
  '/expenses/$expenseId': typeof ExpensesExpenseIdRoute
  '/expenses/new': typeof ExpensesNewRoute
  '/expenses': typeof ExpensesIndexRoute
  '/orders': typeof OrdersIndexRoute
  '/pos': typeof PosIndexRoute
  '/queue-orders': typeof QueueOrdersIndexRoute
  '/reports': typeof ReportsIndexRoute
  '/categories': typeof manageproductsCategoriesIndexRoute
  '/products': typeof manageproductsProductsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/menu': typeof MenuRoute
  '/demo/tanstack-query': typeof DemoTanstackQueryRoute
  '/expenses/$expenseId': typeof ExpensesExpenseIdRoute
  '/expenses/new': typeof ExpensesNewRoute
  '/expenses': typeof ExpensesIndexRoute
  '/orders': typeof OrdersIndexRoute
  '/pos': typeof PosIndexRoute
  '/queue-orders': typeof QueueOrdersIndexRoute
  '/reports': typeof ReportsIndexRoute
  '/categories': typeof manageproductsCategoriesIndexRoute
  '/products': typeof manageproductsProductsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/menu': typeof MenuRoute
  '/demo/tanstack-query': typeof DemoTanstackQueryRoute
  '/expenses/$expenseId': typeof ExpensesExpenseIdRoute
  '/expenses/new': typeof ExpensesNewRoute
  '/expenses/': typeof ExpensesIndexRoute
  '/orders/': typeof OrdersIndexRoute
  '/pos/': typeof PosIndexRoute
  '/queue-orders/': typeof QueueOrdersIndexRoute
  '/reports/': typeof ReportsIndexRoute
  '/(manage products)/categories/': typeof manageproductsCategoriesIndexRoute
  '/(manage products)/products/': typeof manageproductsProductsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/menu'
    | '/demo/tanstack-query'
    | '/expenses/$expenseId'
    | '/expenses/new'
    | '/expenses'
    | '/orders'
    | '/pos'
    | '/queue-orders'
    | '/reports'
    | '/categories'
    | '/products'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/menu'
    | '/demo/tanstack-query'
    | '/expenses/$expenseId'
    | '/expenses/new'
    | '/expenses'
    | '/orders'
    | '/pos'
    | '/queue-orders'
    | '/reports'
    | '/categories'
    | '/products'
  id:
    | '__root__'
    | '/'
    | '/menu'
    | '/demo/tanstack-query'
    | '/expenses/$expenseId'
    | '/expenses/new'
    | '/expenses/'
    | '/orders/'
    | '/pos/'
    | '/queue-orders/'
    | '/reports/'
    | '/(manage products)/categories/'
    | '/(manage products)/products/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  MenuRoute: typeof MenuRoute
  DemoTanstackQueryRoute: typeof DemoTanstackQueryRoute
  ExpensesExpenseIdRoute: typeof ExpensesExpenseIdRoute
  ExpensesNewRoute: typeof ExpensesNewRoute
  ExpensesIndexRoute: typeof ExpensesIndexRoute
  OrdersIndexRoute: typeof OrdersIndexRoute
  PosIndexRoute: typeof PosIndexRoute
  QueueOrdersIndexRoute: typeof QueueOrdersIndexRoute
  ReportsIndexRoute: typeof ReportsIndexRoute
  manageproductsCategoriesIndexRoute: typeof manageproductsCategoriesIndexRoute
  manageproductsProductsIndexRoute: typeof manageproductsProductsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/menu': {
      id: '/menu'
      path: '/menu'
      fullPath: '/menu'
      preLoaderRoute: typeof MenuRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports/': {
      id: '/reports/'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof ReportsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/queue-orders/': {
      id: '/queue-orders/'
      path: '/queue-orders'
      fullPath: '/queue-orders'
      preLoaderRoute: typeof QueueOrdersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pos/': {
      id: '/pos/'
      path: '/pos'
      fullPath: '/pos'
      preLoaderRoute: typeof PosIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/orders/': {
      id: '/orders/'
      path: '/orders'
      fullPath: '/orders'
      preLoaderRoute: typeof OrdersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/expenses/': {
      id: '/expenses/'
      path: '/expenses'
      fullPath: '/expenses'
      preLoaderRoute: typeof ExpensesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/expenses/new': {
      id: '/expenses/new'
      path: '/expenses/new'
      fullPath: '/expenses/new'
      preLoaderRoute: typeof ExpensesNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/expenses/$expenseId': {
      id: '/expenses/$expenseId'
      path: '/expenses/$expenseId'
      fullPath: '/expenses/$expenseId'
      preLoaderRoute: typeof ExpensesExpenseIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/tanstack-query': {
      id: '/demo/tanstack-query'
      path: '/demo/tanstack-query'
      fullPath: '/demo/tanstack-query'
      preLoaderRoute: typeof DemoTanstackQueryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(manage products)/products/': {
      id: '/(manage products)/products/'
      path: '/products'
      fullPath: '/products'
      preLoaderRoute: typeof manageproductsProductsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(manage products)/categories/': {
      id: '/(manage products)/categories/'
      path: '/categories'
      fullPath: '/categories'
      preLoaderRoute: typeof manageproductsCategoriesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  MenuRoute: MenuRoute,
  DemoTanstackQueryRoute: DemoTanstackQueryRoute,
  ExpensesExpenseIdRoute: ExpensesExpenseIdRoute,
  ExpensesNewRoute: ExpensesNewRoute,
  ExpensesIndexRoute: ExpensesIndexRoute,
  OrdersIndexRoute: OrdersIndexRoute,
  PosIndexRoute: PosIndexRoute,
  QueueOrdersIndexRoute: QueueOrdersIndexRoute,
  ReportsIndexRoute: ReportsIndexRoute,
  manageproductsCategoriesIndexRoute: manageproductsCategoriesIndexRoute,
  manageproductsProductsIndexRoute: manageproductsProductsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
