/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as QueueOrdersIndexRouteImport } from './routes/queue-orders/index'
import { Route as PosIndexRouteImport } from './routes/pos/index'
import { Route as OrdersIndexRouteImport } from './routes/orders/index'
import { Route as DemoTanstackQueryRouteImport } from './routes/demo/tanstack-query'
import { Route as manageproductsProductsIndexRouteImport } from './routes/(manage products)/products/index'
import { Route as manageproductsCategoriesIndexRouteImport } from './routes/(manage products)/categories/index'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const QueueOrdersIndexRoute = QueueOrdersIndexRouteImport.update({
  id: '/queue-orders/',
  path: '/queue-orders/',
  getParentRoute: () => rootRouteImport,
} as any)
const PosIndexRoute = PosIndexRouteImport.update({
  id: '/pos/',
  path: '/pos/',
  getParentRoute: () => rootRouteImport,
} as any)
const OrdersIndexRoute = OrdersIndexRouteImport.update({
  id: '/orders/',
  path: '/orders/',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoTanstackQueryRoute = DemoTanstackQueryRouteImport.update({
  id: '/demo/tanstack-query',
  path: '/demo/tanstack-query',
  getParentRoute: () => rootRouteImport,
} as any)
const manageproductsProductsIndexRoute =
  manageproductsProductsIndexRouteImport.update({
    id: '/(manage products)/products/',
    path: '/products/',
    getParentRoute: () => rootRouteImport,
  } as any)
const manageproductsCategoriesIndexRoute =
  manageproductsCategoriesIndexRouteImport.update({
    id: '/(manage products)/categories/',
    path: '/categories/',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/demo/tanstack-query': typeof DemoTanstackQueryRoute
  '/orders': typeof OrdersIndexRoute
  '/pos': typeof PosIndexRoute
  '/queue-orders': typeof QueueOrdersIndexRoute
  '/categories': typeof manageproductsCategoriesIndexRoute
  '/products': typeof manageproductsProductsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/demo/tanstack-query': typeof DemoTanstackQueryRoute
  '/orders': typeof OrdersIndexRoute
  '/pos': typeof PosIndexRoute
  '/queue-orders': typeof QueueOrdersIndexRoute
  '/categories': typeof manageproductsCategoriesIndexRoute
  '/products': typeof manageproductsProductsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/demo/tanstack-query': typeof DemoTanstackQueryRoute
  '/orders/': typeof OrdersIndexRoute
  '/pos/': typeof PosIndexRoute
  '/queue-orders/': typeof QueueOrdersIndexRoute
  '/(manage products)/categories/': typeof manageproductsCategoriesIndexRoute
  '/(manage products)/products/': typeof manageproductsProductsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/demo/tanstack-query'
    | '/orders'
    | '/pos'
    | '/queue-orders'
    | '/categories'
    | '/products'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/demo/tanstack-query'
    | '/orders'
    | '/pos'
    | '/queue-orders'
    | '/categories'
    | '/products'
  id:
    | '__root__'
    | '/'
    | '/demo/tanstack-query'
    | '/orders/'
    | '/pos/'
    | '/queue-orders/'
    | '/(manage products)/categories/'
    | '/(manage products)/products/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DemoTanstackQueryRoute: typeof DemoTanstackQueryRoute
  OrdersIndexRoute: typeof OrdersIndexRoute
  PosIndexRoute: typeof PosIndexRoute
  QueueOrdersIndexRoute: typeof QueueOrdersIndexRoute
  manageproductsCategoriesIndexRoute: typeof manageproductsCategoriesIndexRoute
  manageproductsProductsIndexRoute: typeof manageproductsProductsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/queue-orders/': {
      id: '/queue-orders/'
      path: '/queue-orders'
      fullPath: '/queue-orders'
      preLoaderRoute: typeof QueueOrdersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pos/': {
      id: '/pos/'
      path: '/pos'
      fullPath: '/pos'
      preLoaderRoute: typeof PosIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/orders/': {
      id: '/orders/'
      path: '/orders'
      fullPath: '/orders'
      preLoaderRoute: typeof OrdersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/tanstack-query': {
      id: '/demo/tanstack-query'
      path: '/demo/tanstack-query'
      fullPath: '/demo/tanstack-query'
      preLoaderRoute: typeof DemoTanstackQueryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(manage products)/products/': {
      id: '/(manage products)/products/'
      path: '/products'
      fullPath: '/products'
      preLoaderRoute: typeof manageproductsProductsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(manage products)/categories/': {
      id: '/(manage products)/categories/'
      path: '/categories'
      fullPath: '/categories'
      preLoaderRoute: typeof manageproductsCategoriesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DemoTanstackQueryRoute: DemoTanstackQueryRoute,
  OrdersIndexRoute: OrdersIndexRoute,
  PosIndexRoute: PosIndexRoute,
  QueueOrdersIndexRoute: QueueOrdersIndexRoute,
  manageproductsCategoriesIndexRoute: manageproductsCategoriesIndexRoute,
  manageproductsProductsIndexRoute: manageproductsProductsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
